//Making  Variables
var five = 5;
var ten = 10;
//Test 1;
console.log("Test 1: five is eqaul to 5?");
console.log(five == 5);
//Test 2;
console.log("\nTest 2: ten is equal to 10?");
console.log(ten == 10);
//Test 3;
console.log("\nTest 3: five is not equal to 10?");
console.log(five != 10);
//Test 4;
console.log("\nTest 4: ten is greater than 5?");
console.log(ten > 5);
//Test 5;
console.log("\nTest 5: five is smaller than 10?");
console.log(five < ten);
//Test 6;
console.log("\nTest 6: five is greater than 10?");
console.log(5 > 10);
//Test 7;
console.log("\nTest 7: ten is smaller than 5?");
console.log(ten < 5);
//Test 8;
console.log("\nTest 8: 5 is equall to 10?");
console.log(five == ten);
//Test 9;
console.log("\nTest 9: ten is not equal to 10?");
console.log(ten != 10);
//Test 10;
console.log("\nTest 10: 100 is smaller than 50?");
console.log(100 < 50);
